name: koji
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  intl: ^0.19.0
  uuid: ^4.2.2
  flutter_riverpod: ^2.4.9
  go_router: ^12.0.0
  logger: ^2.0.0
  pdf: ^3.10.7
  printing: ^5.12.0
  path_provider: ^2.1.2
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
